version: "{build}"

clone_depth: 10

branches:
  only:
    - master

install:
    - cinst jdk9 -params 'installdir=C:\\jdk9'
    - SET JAVA_HOME=C:\jdk9
    - SET PATH=C:\jdk9\bin;%PATH%
    - git submodule init
    - git submodule update

build: off

test_script:
  - mvn clean package
