language: java

sudo : false

addons:
  apt:
    packages:
      - oracle-java10-installer

install:
  - git submodule init
  - git submodule update

script: mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)
